### ISSUE TITLE
Ліфт на першому *ViVi* не відображає результат *boys next door*

### ISSUE THREAD

**Issue by Kindrat02** [tanchik-curly/elevators#13]
Severity: S2
Reprorate: 1
Steps to reproduce:
1. Start program
2. See the elevator values that waits for users on first floor - its empty

Expected result: 
The elevator on the ground floor should display its values

**Comment by OleksandrBilan** [comment]
Please, provide the appropriate description: steps to reproduce, severity, frequency and expected result

**Comment by Kindrat02** [comment]
![image](https://user-images.githubusercontent.com/52006668/144289815-3b70bb5e-2854-4161-98f0-12fbf502e793.png)

**Comment by tanchik-curly** [comment]
Oleksand вгомонися і пофікси

**Comment by tanchik-curly** [comment]
Негідник такий

**Comment by tanchik-curly** [comment]
Візьми себе в руки))

**Comment by OleksandrBilan** [comment]
Thanks to @Belgef , @Kindrat02 , @tanchik-curly and , of course, ME for the brilliant and the fastest solution ever made!!!

**Comment by Kindrat02** [comment]
![image](https://user-images.githubusercontent.com/52006668/144320785-10f20a03-08c9-4fe0-87c3-fff099e32803.png)

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144320923-e263281e-4414-48f6-ac26-cf7086f25777.png)
