### ISSUE TITLE
The program throws InterruptedException on 'Reset' button click

### ISSUE THREAD

**Issue by OleksandrBilan** [tanchik-curly/elevators#14]
![image](https://user-images.githubusercontent.com/79528077/144290852-e269f9d1-4a21-4ff5-9ddf-8a4eec9e846b.png)

Steps to reproduce:
1. click the 'start' button
2. click the 'reset' button
3. cry...

Frequency: always
Severity: 100

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144320996-c070d3d4-a80f-494e-a65f-0fce49650ad6.png)

The responsible person

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144321096-f49a13cf-8c8c-4308-ba97-10760ec0940e.png)

The accountable person

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144321147-7c103f19-9d61-454f-824f-14f7cc17cf14.png)

The consulted person

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144321217-283c05c8-9364-4b78-8b08-a61123c3934d.png)

The informed person

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144321271-4f91cb68-39e9-45eb-be65-4f8b80c5a11d.png)

The best person

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144321378-e245fd14-5044-430b-9187-23a3c4138b69.png)

The person

**Comment by OleksandrBilan** [comment]
![image](https://user-images.githubusercontent.com/79528077/144321488-f486d725-a16b-4357-b299-efdce23693c5.png)

The

**Comment by RamzesUAA** [comment]
Looks good. Approved. Well job )
